# "S", "FBT", "T20" might not be necessary
# might wanna add "DTZ"
select = ["F", "E", "W", "C90", "I", "N", "D", "UP", "ANN", "ASYNC", "S", "BLE",
          "FBT", "B", "A", "COM", "C4", "T10", "EM", "ISC", "ICN", "G", "PIE", "T20",
          "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "ERA", "PGH", "PL",
          "TRY", "FLY", "PERF", "FURB", "LOG", "RUF"]
exclude = [
    "venv",
    ".mypy_cache",
    ".ruff_cache",
    ".gitignore",
]

# PEP-8 says 80 chars but it's too low imo
line-length = 120

[pycodestyle]
max-doc-length = 120
