name: Ruff PR Check
on:
  pull_request:

jobs:
  ruff:
    name: Ruff Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ruff
        run: pip install ruff

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.py$' | xargs)" >> $GITHUB_OUTPUT

      - name: Run Ruff
        run: |
          if [ -f ruff.toml ]; then
            if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
              ruff check ${{ steps.changed-files.outputs.files }}
            else
              echo "No Python files changed in this PR."
            fi
          else
            echo "ruff.toml file not found, using default Ruff settings"
            if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
              ruff check ${{ steps.changed-files.outputs.files }}
            else
              echo "No Python files changed in this PR."
            fi
          fi
